name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false  # Или true для публикации в Docker Hub
          tags: |
            
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest          

      - name: Run tests
      - run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -f http://localhost:8000/docs || exit 1

      - name: Push Docker image to registry
        if: success()
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }},
             ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest  
